server:
  port: 8080

spring:
  application:
    name: cloudnest-backend

  datasource:
    url: jdbc:mysql://localhost:3306/cloudnest_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: '@Sumeet16'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  jwt:
    secret: cloudnest-super-secret-key-change-this-in-production-please-2026
    expiration-ms: 86400000

  storage:
    local-disk-path: ./storage/local-disk
    simulated-s3-path: ./storage/simulated-s3
    temp-path: ./storage/temp

  google:
    client-id: YOUR_GOOGLE_CLIENT_ID
    client-secret: YOUR_GOOGLE_CLIENT_SECRET
    redirect-uri: http://localhost:8080/api/cloud-providers/google/callback
    application-name: CloudNest
  
  backblaze:
    endpoint: https://s3.us-east-005.backblazeb2.com
    region: us-east-005
    access-key-id: '0052509c551fc7f0000000002'
    secret-access-key: 'K005NOt/iOWhHdq+OUOPQGvyzXUg0eQ'
    bucket-name: cloudnest-backups

  quotas:
    google-drive-bytes: 16106127360
    local-disk-bytes: 107374182400
    simulated-s3-bytes: 5368709120
    backblaze-bytes: 1073741824

  encryption:
    secret-key: CloudNest2026AES256SecretKey!!!!

logging:
  level:
    com.cloudnest: DEBUG
